### ISSUE TITLE
No Confirm on Revive

### ISSUE THREAD

**Issue by IdzyQ** [Goltred/tornscripts#12]
I have this script that removes the need to click confirmation yes/no on certain actions. For example, item use, item buy, bazaar buy etc.
  https://greasyfork.org/scripts/390987-torn-no-confirm/code/TORN:%20No%20Confirm.user.js

Can we get something like this but for the revive button? 1-click reviving ftw!

**Comment by Goltred** [comment]
Hey! Doing so would break the scripting rules I believe? As it would require an automated click on the yes link once it begins available...

I looked for better ways of doing revives faster but couldn't find anything, mostly because of the way the revive ui works in turn :(

**Comment by Fogest** [comment]
@Goltred From what I understand this no-confirm on the revives would be allowed. That no-confirm is allowed because the user still has to click to revive, this just skips the confirmation. The author of that other one I believe had checked with Torn Staff to make sure.

**Comment by Goltred** [comment]
This is done on version 3.0.0 of torn hospital script :)
