### ISSUE TITLE
Add auto-refresh every x seconds to hospital script

### ISSUE THREAD

**Issue by Fogest** [Goltred/tornscripts#16]
**Describe the solution you'd like**
It would be neat to have the faction page auto-refresh every x seconds. It would work the same way it does when you click the "refresh" button. This would allow you to have the page open on another screen and not have to keep clicking revive while doing something else at the same time.

**Comment by Goltred** [comment]
I am not sure how much this would fall into botting land for torn, since you are not loading the page manually.
There's also a bunch of other extensions that do precisely that, so I am not sure that it is worth the (little indeed) effort

**Comment by Fogest** [comment]
That is true, maybe it is worth just using a different extension for this kind of purpose. Probably gives more customization anyway doing it that way :)
